/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import File.AudioVisualFile;
import File.RequestAudioVisualFile;
import cr.ac.ucr.IF3000.BiblioTech.domain.AudioVisual;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestAudioVisual;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel
 */
public class ListOfAvailableAudioVisuals extends javax.swing.JFrame {

    /**
     * Creates new form ListOfAvailableAudioVisuals
     */
    public ListOfAvailableAudioVisuals() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            showTable(lvl_availableAudio);
        } catch (IOException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_InfoListAudio = new javax.swing.JLabel();
        btn_BackBooksRecord = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lvl_availableAudio = new javax.swing.JTable();
        lbl_StuRecedBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(948, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_InfoListAudio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_InfoListAudio.setText("Audiovisuals Recorded Available");
        getContentPane().add(lbl_InfoListAudio);
        lbl_InfoListAudio.setBounds(0, 11, 396, 30);

        btn_BackBooksRecord.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackBooksRecord.setText("Back");
        btn_BackBooksRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackBooksRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_BackBooksRecord);
        btn_BackBooksRecord.setBounds(80, 401, 100, 40);

        lvl_availableAudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equitment Name", "Brand", "Available Audiovisuals", "Amount"
            }
        ));
        jScrollPane1.setViewportView(lvl_availableAudio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(245, 59, 616, 402);

        lbl_StuRecedBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoBasico.jpg"))); // NOI18N
        getContentPane().add(lbl_StuRecedBackground);
        lbl_StuRecedBackground.setBounds(0, 0, 970, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTable(JTable table) throws IOException {
        File file = new File("./AudioVisual.dat");
        AudioVisualFile audioVisuals = new AudioVisualFile(file);
        RequestAudioVisualFile audioFile = new RequestAudioVisualFile();
        AudioVisual allAudioTemp;
        int available = 0;
        ArrayList<AudioVisual> listOfAllAudio = audioVisuals.getAudioList();
        ArrayList<RequestAudioVisual> myArrayList = audioFile.getLoanList();
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        table = new JTable(modelo);
        for(int c=0;c<listOfAllAudio.size();c++){
            for(int i=0;i<myArrayList.size();i++){
                if(myArrayList.get(i).getName().equals(listOfAllAudio.get(c).getName()))
                    available+=1;
            }
            allAudioTemp = listOfAllAudio.get(c);
            if(available>0){
                Object obj[] = new Object[]{
                allAudioTemp.getName(), allAudioTemp.getBrand(), allAudioTemp.getAmount()-available, allAudioTemp.getAmount()
                };
                modelo.addRow(obj);
                available = 0;
            }else{
                Object obj[] = new Object[]{
                allAudioTemp.getName(), allAudioTemp.getBrand(), allAudioTemp.getAmount(), allAudioTemp.getAmount()
                };
                modelo.addRow(obj);
            }
        }
        table.setModel(modelo);
    }
    
    private void btn_BackBooksRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackBooksRecordActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackBooksRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfAvailableAudioVisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfAvailableAudioVisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfAvailableAudioVisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfAvailableAudioVisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfAvailableAudioVisuals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackBooksRecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_InfoListAudio;
    private javax.swing.JLabel lbl_StuRecedBackground;
    private javax.swing.JTable lvl_availableAudio;
    // End of variables declaration//GEN-END:variables
}
