/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import File.StudentFile;
import cr.ac.ucr.IF3000.BiblioTech.domain.Student;

/**
 *
 * @author Max
 */
public class ListOfStudents extends javax.swing.JFrame {

    /**
     * Creates new form ListOfStudents
     */
    public ListOfStudents() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lvl_StudentList = new javax.swing.JTable();
        btn_BackStudentsRecord = new javax.swing.JButton();
        cb_choise = new javax.swing.JComboBox<String>();
        lbl_StuRecedBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(948, 555));
        setMinimumSize(new java.awt.Dimension(948, 555));
        setPreferredSize(new java.awt.Dimension(948, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Students Recorded");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 230, 30);

        lvl_StudentList.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lvl_StudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Mayor", "Year of Income", "ID"
            }
        ));
        jScrollPane2.setViewportView(lvl_StudentList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 40, 660, 402);

        btn_BackStudentsRecord.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackStudentsRecord.setText("Back");
        btn_BackStudentsRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackStudentsRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_BackStudentsRecord);
        btn_BackStudentsRecord.setBounds(90, 410, 100, 40);

        cb_choise.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_choise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mayor", "Agronomy", "Computing", "Education" }));
        cb_choise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_choiseActionPerformed(evt);
            }
        });
        getContentPane().add(cb_choise);
        cb_choise.setBounds(70, 210, 110, 40);

        lbl_StuRecedBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoBasico.jpg"))); // NOI18N
        getContentPane().add(lbl_StuRecedBackground);
        lbl_StuRecedBackground.setBounds(-10, 0, 1060, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackStudentsRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackStudentsRecordActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackStudentsRecordActionPerformed

    private void cb_choiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_choiseActionPerformed
        // TODO add your handling code here:
        String item=cb_choise.getSelectedItem().toString();
        try {
             File file = new File("./student.dat");
             StudentFile st = new StudentFile(file);

            
        
        if(item.equals("Agronomy")){
            limpiarTabla();
            showTable(lvl_StudentList,st.ordenaAlfabeticamente(st.getMayors("A")));
        }else if (item.equals("Computing")){
            limpiarTabla();
            showTable(lvl_StudentList,st.ordenaAlfabeticamente(st.getMayors("I")));
        }else if (item.equals("Education")){
            limpiarTabla();
            showTable(lvl_StudentList,st.ordenaAlfabeticamente(st.getMayors("E")));
        }
        } catch (IOException e) {
            System.err.println("No match found vehicles");
        }

    }//GEN-LAST:event_cb_choiseActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void limpiarTabla(){
        try {
            DefaultTableModel modelo=(DefaultTableModel) lvl_StudentList.getModel();
            int filas=lvl_StudentList.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            System.err.println("The table couldn´t be clear");
        }
       
    }
    
    public void showTable(JTable table, ArrayList<Student> a) throws IOException {
        File file = new File("./student.dat");
        StudentFile studentFile = new StudentFile(file);
        Student student = new Student();
        ArrayList<Student> myArrayList = a;
        
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        table = new JTable(modelo);
        for(int i=0;i<myArrayList.size();i++){
            student = myArrayList.get(i);
            Object obj[] = new Object[]{
                student.getName(),student.getMayor(),student.getYearIncome(),student.getId()};
            modelo.addRow(obj);
        }
        
        lvl_StudentList.setModel(modelo);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackStudentsRecord;
    private javax.swing.JComboBox<String> cb_choise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_StuRecedBackground;
    private javax.swing.JTable lvl_StudentList;
    // End of variables declaration//GEN-END:variables
}
