/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import File.RequestBookFile;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestBook;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel
 */
public class ListOfLoanBook extends javax.swing.JFrame {

    /**
     * Creates new form ListOfLoanBook
     */
    public ListOfLoanBook() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            showTable(lvl_loanBooks);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_InfoListBooks = new javax.swing.JLabel();
        btn_BackBooksRecord = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lvl_loanBooks = new javax.swing.JTable();
        lbl_StuRecedBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(948, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_InfoListBooks.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_InfoListBooks.setText("Loan Books");
        getContentPane().add(lbl_InfoListBooks);
        lbl_InfoListBooks.setBounds(10, 10, 167, 30);

        btn_BackBooksRecord.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackBooksRecord.setText("Back");
        btn_BackBooksRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackBooksRecordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_BackBooksRecord);
        btn_BackBooksRecord.setBounds(29, 415, 100, 40);

        lvl_loanBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Student", "Date of removing book", "Date of delivery book", "Title", "Author(s)"
            }
        ));
        jScrollPane1.setViewportView(lvl_loanBooks);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(156, 59, 598, 402);

        lbl_StuRecedBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoBasico.jpg"))); // NOI18N
        getContentPane().add(lbl_StuRecedBackground);
        lbl_StuRecedBackground.setBounds(0, 0, 970, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTable(JTable table) throws IOException {
        RequestBookFile bookFile = new RequestBookFile();
        RequestBook bookTemp;
        ArrayList<RequestBook> myArrayList = bookFile.getLoanList();
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        table = new JTable(modelo);
        for(int i=0;i<myArrayList.size();i++){
            bookTemp = myArrayList.get(i);
            Object obj[] = new Object[]{
                bookTemp.getId_card(), bookTemp.getDate_remove(), bookTemp.getDate_delivery(), bookTemp.getTitle(), bookTemp.getAuthors()
            };
            modelo.addRow(obj);
        }
        
        table.setModel(modelo);
    }
    
    private void btn_BackBooksRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackBooksRecordActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackBooksRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfLoanBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackBooksRecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_InfoListBooks;
    private javax.swing.JLabel lbl_StuRecedBackground;
    private javax.swing.JTable lvl_loanBooks;
    // End of variables declaration//GEN-END:variables
}
