/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import com.mxrck.autocompleter.TextAutoCompleter;
import File.BooksFile;
import cr.ac.ucr.IF3000.BiblioTech.domain.Books;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestBook;
import cr.ac.ucr.IF3000.BiblioTech.domain.Student;
import File.RequestBookFile;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;


/**
 *
 * @author Emmanuel
 */
public class LoanBooks extends javax.swing.JFrame {

    /**
     * Creates new form LoanBooks
     */
    public LoanBooks() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            autoComplete();
        } catch (IOException e) {
        }
        SearchStudent student = new SearchStudent();
        tfd_idStudent.setText(student.getIdStudent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titleloanBooks = new javax.swing.JLabel();
        jd_removing = new com.toedter.calendar.JDateChooser();
        jd_delivery = new com.toedter.calendar.JDateChooser();
        lbl_removing = new javax.swing.JLabel();
        lbl_delivery = new javax.swing.JLabel();
        btn_loan = new javax.swing.JButton();
        lbl_search = new javax.swing.JLabel();
        lbl_book = new javax.swing.JLabel();
        tfd_book = new javax.swing.JTextField();
        tfd_search = new javax.swing.JTextField();
        btn_BackSearchStudent = new javax.swing.JButton();
        tfd_idStudent = new javax.swing.JTextField();
        lbl_idStudent = new javax.swing.JLabel();
        lbl_StuRecedBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(948, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_titleloanBooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titleloanBooks.setText("Loan Book");
        getContentPane().add(lbl_titleloanBooks);
        lbl_titleloanBooks.setBounds(313, 11, 84, 22);
        getContentPane().add(jd_removing);
        jd_removing.setBounds(520, 240, 168, 30);
        getContentPane().add(jd_delivery);
        jd_delivery.setBounds(520, 310, 168, 30);

        lbl_removing.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_removing.setText("Date of removing book");
        getContentPane().add(lbl_removing);
        lbl_removing.setBounds(170, 250, 143, 17);

        lbl_delivery.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_delivery.setText("Date of delivey book");
        getContentPane().add(lbl_delivery);
        lbl_delivery.setBounds(172, 312, 129, 17);

        btn_loan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_loan.setText("Request loan");
        btn_loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_loan);
        btn_loan.setBounds(360, 370, 130, 40);

        lbl_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_search.setText("Search book for code or title");
        getContentPane().add(lbl_search);
        lbl_search.setBounds(175, 100, 179, 17);

        lbl_book.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_book.setText("Book");
        getContentPane().add(lbl_book);
        lbl_book.setBounds(190, 190, 32, 17);

        tfd_book.setEditable(false);
        getContentPane().add(tfd_book);
        tfd_book.setBounds(350, 180, 332, 30);

        tfd_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfd_searchKeyTyped(evt);
            }
        });
        getContentPane().add(tfd_search);
        tfd_search.setBounds(280, 130, 406, 40);

        btn_BackSearchStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackSearchStudent.setText("Back");
        btn_BackSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackSearchStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_BackSearchStudent);
        btn_BackSearchStudent.setBounds(46, 376, 100, 40);

        tfd_idStudent.setEditable(false);
        tfd_idStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_idStudentActionPerformed(evt);
            }
        });
        getContentPane().add(tfd_idStudent);
        tfd_idStudent.setBounds(410, 50, 268, 30);

        lbl_idStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_idStudent.setText("Id student:");
        getContentPane().add(lbl_idStudent);
        lbl_idStudent.setBounds(175, 50, 66, 17);

        lbl_StuRecedBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoBasico.jpg"))); // NOI18N
        getContentPane().add(lbl_StuRecedBackground);
        lbl_StuRecedBackground.setBounds(0, 0, 970, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertLoan(){
        try {
            File file = new File("./Books.dat");
            BooksFile bookFile = new BooksFile(file);
            ArrayList<Books> myArrayList = bookFile.getBooksList();
            Books bookTemp = new Books();
            for(int i= 0;i<myArrayList.size();i++){
                if(myArrayList.get(i).getTitle().equals(tfd_book.getText()))
                    bookTemp = myArrayList.get(i);
            }
            if(bookTemp == null){
                System.err.println("The book couldn't be found in the file");
            }else{
                RequestBookFile loanBook = new RequestBookFile();
                String formato = "dd/MM/yyyy";
                String card_student = tfd_idStudent.getText();
                Date date1 = jd_removing.getDate();
                Date date2 = jd_delivery.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String date_removing = sdf.format(date1);
                String date_delivery = sdf.format(date2);
                String titleBook = tfd_book.getText();
                String authors= bookTemp.getAuthors();
                int amount = bookTemp.getAmount();
                ArrayList<RequestBook> listLoan = loanBook.getLoanList();
                int available = 0;
                if(listLoan.size()>0){
                    for(int c=0;c<listLoan.size();c++){
                        if(listLoan.get(c).getTitle().equals(titleBook)){
                            available = listLoan.get(c).getAvailable()-1;
                        }
                    }
                }else{
                    available = bookTemp.getAmount()-1;
                }
                RequestBook rBook = new RequestBook(card_student, available, date_removing, date_delivery, titleBook, authors, bookTemp.getType(), bookTemp.getCode(), amount, bookTemp.getAge());
                if(available>=0){
                    loanBook.insertLoanBook(rBook);
                }
                else{
                    System.err.println("Don´t found book available");
                }
                tfd_search.setText("");
                tfd_book.setText("");
                jd_removing.setDateFormatString("");
                jd_delivery.setDateFormatString("");
                tfd_search.requestFocus();
            }
        } catch (Exception e) {
        }
    }
    
    private void tfd_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfd_searchKeyTyped
        String titleBook = tfd_search.getText();
        String book = "";
        try {
            File file = new File("./Books.dat");
            BooksFile bookFile = new BooksFile(file);
            ArrayList<Books> listOfBook = bookFile.getBooksList();
            for(int i=0;i<listOfBook.size();i++){
                if(listOfBook.get(i).getCode().equals(titleBook)){
                    book=listOfBook.get(i).getTitle();
                }else if(listOfBook.get(i).getTitle().equals(titleBook)){
                    book=listOfBook.get(i).getTitle();
                }
            }
        } catch (IOException e) {
        }
        
        tfd_book.setText(book);
          
    }//GEN-LAST:event_tfd_searchKeyTyped

    private void btn_loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loanActionPerformed
        if(!tfd_idStudent.getText().equals("") || !jd_removing.getDate().toString().equals("") || !jd_delivery.getDate().toString().equals("")){
            insertLoan();
        }
        
    }//GEN-LAST:event_btn_loanActionPerformed

    private void btn_BackSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackSearchStudentActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackSearchStudentActionPerformed

    private void tfd_idStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_idStudentActionPerformed
        
    }//GEN-LAST:event_tfd_idStudentActionPerformed

    public void autoComplete() throws IOException{
        TextAutoCompleter complete = new TextAutoCompleter(tfd_search);
        File file = new File("./Books.dat");
        BooksFile bookFile = new BooksFile(file);
        ArrayList<Books> myArrayList = bookFile.getBooksList();
        Books bookTemp = new Books();
        for(int i= 0;i<myArrayList.size();i++){
            bookTemp = myArrayList.get(i);
            complete.addItem(bookTemp.getTitle());
            complete.addItem(bookTemp.getCode());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackSearchStudent;
    private javax.swing.JButton btn_loan;
    private com.toedter.calendar.JDateChooser jd_delivery;
    private com.toedter.calendar.JDateChooser jd_removing;
    private javax.swing.JLabel lbl_StuRecedBackground;
    private javax.swing.JLabel lbl_book;
    private javax.swing.JLabel lbl_delivery;
    private javax.swing.JLabel lbl_idStudent;
    private javax.swing.JLabel lbl_removing;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_titleloanBooks;
    private javax.swing.JTextField tfd_book;
    private javax.swing.JTextField tfd_idStudent;
    private javax.swing.JTextField tfd_search;
    // End of variables declaration//GEN-END:variables
}
