/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import com.mxrck.autocompleter.TextAutoCompleter;
import cr.ac.ucr.IF3000.BiblioTech.domain.AudioVisual;
import cr.ac.ucr.IF3000.BiblioTech.domain.Books;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestAudioVisual;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestBook;
import File.AudioVisualFile;
import File.BooksFile;
import File.RequestAudioVisualFile;
import File.RequestBookFile;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Emmanuel
 */
public class LoanAudioVisual extends javax.swing.JFrame {

    /**
     * Creates new form LoanAudioBook
     */
    public LoanAudioVisual() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            autoComplete();
        } catch (IOException e) {
        }
        SearchStudent student = new SearchStudent();
        tfd_idStudent.setText(student.getIdStudent());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_removing = new javax.swing.JLabel();
        lbl_delivery = new javax.swing.JLabel();
        lbl_titleloanAudio = new javax.swing.JLabel();
        btn_loan = new javax.swing.JButton();
        tfd_search = new javax.swing.JTextField();
        lbl_search = new javax.swing.JLabel();
        lbl_audio = new javax.swing.JLabel();
        tfd_audio = new javax.swing.JTextField();
        btn_BackSearchStudent = new javax.swing.JButton();
        lbl_idStudent = new javax.swing.JLabel();
        tfd_idStudent = new javax.swing.JTextField();
        jd_removing = new com.toedter.calendar.JDateChooser();
        jd_delivery = new com.toedter.calendar.JDateChooser();
        lbl_StuRecedBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(948, 555));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_removing.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_removing.setText("Date of removing audiovisual");
        getContentPane().add(lbl_removing);
        lbl_removing.setBounds(130, 249, 200, 17);

        lbl_delivery.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_delivery.setText("Date of delivey audiovisual");
        getContentPane().add(lbl_delivery);
        lbl_delivery.setBounds(140, 328, 180, 17);

        lbl_titleloanAudio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titleloanAudio.setText("Loan Audiovisual");
        getContentPane().add(lbl_titleloanAudio);
        lbl_titleloanAudio.setBounds(313, 11, 133, 22);

        btn_loan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_loan.setText("Request loan");
        btn_loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_loan);
        btn_loan.setBounds(340, 390, 130, 40);

        tfd_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfd_searchKeyTyped(evt);
            }
        });
        getContentPane().add(tfd_search);
        tfd_search.setBounds(180, 120, 437, 32);

        lbl_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_search.setText("Search audiovisual for code or title");
        getContentPane().add(lbl_search);
        lbl_search.setBounds(180, 100, 250, 17);

        lbl_audio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_audio.setText("AudioVisual");
        getContentPane().add(lbl_audio);
        lbl_audio.setBounds(180, 180, 90, 14);

        tfd_audio.setEditable(false);
        getContentPane().add(tfd_audio);
        tfd_audio.setBounds(290, 180, 332, 30);

        btn_BackSearchStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackSearchStudent.setText("Back");
        btn_BackSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackSearchStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_BackSearchStudent);
        btn_BackSearchStudent.setBounds(72, 393, 100, 40);

        lbl_idStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_idStudent.setText("Id student:");
        getContentPane().add(lbl_idStudent);
        lbl_idStudent.setBounds(206, 59, 80, 17);

        tfd_idStudent.setEditable(false);
        tfd_idStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_idStudentActionPerformed(evt);
            }
        });
        getContentPane().add(tfd_idStudent);
        tfd_idStudent.setBounds(344, 56, 268, 30);
        getContentPane().add(jd_removing);
        jd_removing.setBounds(390, 250, 210, 20);
        getContentPane().add(jd_delivery);
        jd_delivery.setBounds(390, 330, 210, 20);

        lbl_StuRecedBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoBasico.jpg"))); // NOI18N
        getContentPane().add(lbl_StuRecedBackground);
        lbl_StuRecedBackground.setBounds(0, 0, 970, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //texfield autocomplete
    public void autoComplete() throws IOException{
        TextAutoCompleter complete = new TextAutoCompleter(tfd_search);
        File file = new File("./AudioVisual.dat");
        AudioVisualFile audioFile = new AudioVisualFile(file);
        ArrayList<AudioVisual> myArrayList = audioFile.getAudioList();
        AudioVisual audioTemp = new AudioVisual();
        for(int i= 0;i<myArrayList.size();i++){
            audioTemp = myArrayList.get(i);
            complete.addItem(audioTemp.getName());
            complete.addItem(audioTemp.getCode());
        }
    }//end method
    //method to save the loan audiovisual
    public void insertAudioVisual(){
        try {
            File file = new File("./AudioVisual.dat");
            AudioVisualFile audioFile = new AudioVisualFile(file);
            ArrayList<AudioVisual> myArrayList = audioFile.getAudioList();
            AudioVisual audioTemp = new AudioVisual();
            for(int i= 0;i<myArrayList.size();i++){
                if(myArrayList.get(i).getName().equals(tfd_audio.getText()))
                    audioTemp = myArrayList.get(i);
            }
            if(audioTemp == null){
                System.err.println("The audio visual couldn't be found in the file");
            }else{
                SearchStudent get_id = new SearchStudent();
                RequestAudioVisualFile loanAudio = new RequestAudioVisualFile();
                String card_Student = tfd_idStudent.getText();
                String formato = "dd/MM/yyyy";
                Date date1 = jd_removing.getDate();
                Date date2 = jd_delivery.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String date_removing = sdf.format(date1);
                String date_delivery = sdf.format(date2);
                String titleAudio = tfd_audio.getText();
                String brand= audioTemp.getBrand();
                int amount = audioTemp.getAmount();
                ArrayList<RequestAudioVisual> listLoan = loanAudio.getLoanList();
                int available = 0;
                if(listLoan.size()>0){
                    for(int c=0;c<listLoan.size();c++){
                        if(listLoan.get(c).getName().equals(titleAudio)){
                            available = listLoan.get(c).getAvailable()-1;
                        }
                    }
                }else{
                    available = audioTemp.getAmount()-1;
                }
                RequestAudioVisual rAudioVisual = new RequestAudioVisual(card_Student, available, date_removing, date_delivery, titleAudio, brand, audioTemp.getModel(), audioTemp.getCode(), amount);
                if(available>=0){
                    loanAudio.insertLoanAudio(rAudioVisual);
                }
                else{
                    System.err.println("Don´t found audio visual available");
                }
                tfd_search.setText("");
                tfd_audio.setText("");
                jd_removing.setDateFormatString("");
                jd_delivery.setDateFormatString("");
                tfd_search.requestFocus();
            }
        } catch (IOException e) {
        }
    }
    
    private void tfd_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfd_searchKeyTyped
        String titleAudio = tfd_search.getText();
        String audio = "";
        try {
            File file = new File("./AudioVisual.dat");
            AudioVisualFile audioFile = new AudioVisualFile(file);
            ArrayList<AudioVisual> listOfAudio = audioFile.getAudioList();
            for(int i=0;i<listOfAudio.size();i++){
                String code= ""+listOfAudio.get(i).getCode();
                if(code.equals(titleAudio)){
                    audio=listOfAudio.get(i).getName();
                }else if(listOfAudio.get(i).getName().equals(titleAudio)){
                    audio=listOfAudio.get(i).getName();
                }
            }
        } catch (IOException e) {
        }
        
        tfd_audio.setText(audio);
    }//GEN-LAST:event_tfd_searchKeyTyped

    private void btn_loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loanActionPerformed
        if(!tfd_idStudent.getText().equals("") || !jd_removing.getDate().toString().equals("") || !jd_delivery.getDate().toString().equals("")){
            insertAudioVisual();
        }
    }//GEN-LAST:event_btn_loanActionPerformed

    private void btn_BackSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackSearchStudentActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackSearchStudentActionPerformed

    private void tfd_idStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_idStudentActionPerformed

    }//GEN-LAST:event_tfd_idStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAudioVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackSearchStudent;
    private javax.swing.JButton btn_loan;
    private com.toedter.calendar.JDateChooser jd_delivery;
    private com.toedter.calendar.JDateChooser jd_removing;
    private javax.swing.JLabel lbl_StuRecedBackground;
    private javax.swing.JLabel lbl_audio;
    private javax.swing.JLabel lbl_delivery;
    private javax.swing.JLabel lbl_idStudent;
    private javax.swing.JLabel lbl_removing;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_titleloanAudio;
    private javax.swing.JTextField tfd_audio;
    private javax.swing.JTextField tfd_idStudent;
    private javax.swing.JTextField tfd_search;
    // End of variables declaration//GEN-END:variables
}
