/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Max
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        
        initComponents();
        setLocationRelativeTo(null);
        
        
         
    }
    
//        setSize(300, 300);
//        SetPrincipalImageBackground set = new SetPrincipalImageBackground();
//        this.add(set, BorderLayout.CENTER);
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_PrincipalExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_Backgroud = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mu_Record = new javax.swing.JMenu();
        muRe_Materials = new javax.swing.JMenuItem();
        muRe_Student = new javax.swing.JMenuItem();
        mu_Tables = new javax.swing.JMenu();
        muTa_Students = new javax.swing.JMenuItem();
        muTa_Books = new javax.swing.JMenuItem();
        muTa_AudioVisual = new javax.swing.JMenuItem();
        menuItem_AvailableBooks = new javax.swing.JMenuItem();
        menuItem_AvailableAudio = new javax.swing.JMenuItem();
        menuItem_loanBooks = new javax.swing.JMenuItem();
        menuItem_loanAudiovisuals = new javax.swing.JMenuItem();
        mu_Loans = new javax.swing.JMenu();
        muLo_Search = new javax.swing.JMenuItem();
        mu_Returns = new javax.swing.JMenu();
        muRet_Book = new javax.swing.JMenuItem();
        muItemRet_AudioVisual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(948, 575));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_PrincipalExit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_PrincipalExit.setText("Exit");
        btn_PrincipalExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrincipalExitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_PrincipalExit);
        btn_PrincipalExit.setBounds(770, 400, 100, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        lbl_Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.jpg"))); // NOI18N
        lbl_Backgroud.setName(""); // NOI18N
        getContentPane().add(lbl_Backgroud);
        lbl_Backgroud.setBounds(0, 0, 940, 530);

        mu_Record.setText("Record");

        muRe_Materials.setText("Materials");
        muRe_Materials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muRe_MaterialsActionPerformed(evt);
            }
        });
        mu_Record.add(muRe_Materials);

        muRe_Student.setText("Student");
        muRe_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muRe_StudentActionPerformed(evt);
            }
        });
        mu_Record.add(muRe_Student);

        jMenuBar1.add(mu_Record);

        mu_Tables.setText("Report");

        muTa_Students.setText("Students");
        muTa_Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTa_StudentsActionPerformed(evt);
            }
        });
        mu_Tables.add(muTa_Students);

        muTa_Books.setText("Books");
        muTa_Books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTa_BooksActionPerformed(evt);
            }
        });
        mu_Tables.add(muTa_Books);

        muTa_AudioVisual.setText("AudioVisual");
        muTa_AudioVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTa_AudioVisualActionPerformed(evt);
            }
        });
        mu_Tables.add(muTa_AudioVisual);

        menuItem_AvailableBooks.setText("Books Available");
        menuItem_AvailableBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_AvailableBooksActionPerformed(evt);
            }
        });
        mu_Tables.add(menuItem_AvailableBooks);

        menuItem_AvailableAudio.setText("Audiovisuals Available");
        menuItem_AvailableAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_AvailableAudioActionPerformed(evt);
            }
        });
        mu_Tables.add(menuItem_AvailableAudio);

        menuItem_loanBooks.setText("Loan of books");
        menuItem_loanBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_loanBooksActionPerformed(evt);
            }
        });
        mu_Tables.add(menuItem_loanBooks);

        menuItem_loanAudiovisuals.setText("Loan of audiovisuals");
        menuItem_loanAudiovisuals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_loanAudiovisualsActionPerformed(evt);
            }
        });
        mu_Tables.add(menuItem_loanAudiovisuals);

        jMenuBar1.add(mu_Tables);

        mu_Loans.setText("Loans");
        mu_Loans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mu_LoansActionPerformed(evt);
            }
        });

        muLo_Search.setText("Books or AudioVisual");
        muLo_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muLo_SearchActionPerformed(evt);
            }
        });
        mu_Loans.add(muLo_Search);

        jMenuBar1.add(mu_Loans);

        mu_Returns.setText("Returns");

        muRet_Book.setText("Book");
        muRet_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muRet_BookActionPerformed(evt);
            }
        });
        mu_Returns.add(muRet_Book);

        muItemRet_AudioVisual.setText("AudioVisual");
        muItemRet_AudioVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muItemRet_AudioVisualActionPerformed(evt);
            }
        });
        mu_Returns.add(muItemRet_AudioVisual);

        jMenuBar1.add(mu_Returns);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muRe_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muRe_StudentActionPerformed
        // TODO add your handling code here:
        RecordStudent rs = new RecordStudent();
        rs.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_muRe_StudentActionPerformed

    private void muTa_StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTa_StudentsActionPerformed
        // TODO add your handling code here:
        ListOfStudents list = new ListOfStudents();
        list.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_muTa_StudentsActionPerformed

    private void btn_PrincipalExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrincipalExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_PrincipalExitActionPerformed

    private void mu_LoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mu_LoansActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mu_LoansActionPerformed

    private void muLo_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muLo_SearchActionPerformed
        // TODO add your handling code here:
        SearchStudent ss=new SearchStudent();
        ss.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_muLo_SearchActionPerformed

    private void muRet_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muRet_BookActionPerformed
        // TODO add your handling code here:
        ReturnMaterial rm = new ReturnMaterial();
        rm.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_muRet_BookActionPerformed

    private void muRe_MaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muRe_MaterialsActionPerformed
        // TODO add your handling code here:
        LogAudioVisual log = new LogAudioVisual();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_muRe_MaterialsActionPerformed

    private void muTa_BooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTa_BooksActionPerformed
        // TODO add your handling code here:
        ListOfBooks list = new ListOfBooks();
        list.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_muTa_BooksActionPerformed

    private void muTa_AudioVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTa_AudioVisualActionPerformed
        // TODO add your handling code here:
        ListOfAudioVisuals list = new ListOfAudioVisuals();
        list.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_muTa_AudioVisualActionPerformed

    private void menuItem_AvailableBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_AvailableBooksActionPerformed
        ListOfAvailableBooks listBooks = new ListOfAvailableBooks();
        listBooks.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItem_AvailableBooksActionPerformed

    private void menuItem_AvailableAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_AvailableAudioActionPerformed
        ListOfAvailableAudioVisuals listAudio = new ListOfAvailableAudioVisuals();
        listAudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItem_AvailableAudioActionPerformed

    private void menuItem_loanBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_loanBooksActionPerformed
        ListOfLoanBook loanBook = new ListOfLoanBook();
        loanBook.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItem_loanBooksActionPerformed

    private void menuItem_loanAudiovisualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_loanAudiovisualsActionPerformed
        ListOfLoanAudiovisuals loanAudio = new ListOfLoanAudiovisuals();
        loanAudio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItem_loanAudiovisualsActionPerformed

    private void muItemRet_AudioVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muItemRet_AudioVisualActionPerformed
        // TODO add your handling code here:
        ReturnAudioVisual re = new ReturnAudioVisual();
        re.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_muItemRet_AudioVisualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PrincipalExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_Backgroud;
    private javax.swing.JMenuItem menuItem_AvailableAudio;
    private javax.swing.JMenuItem menuItem_AvailableBooks;
    private javax.swing.JMenuItem menuItem_loanAudiovisuals;
    private javax.swing.JMenuItem menuItem_loanBooks;
    private javax.swing.JMenuItem muItemRet_AudioVisual;
    private javax.swing.JMenuItem muLo_Search;
    private javax.swing.JMenuItem muRe_Materials;
    private javax.swing.JMenuItem muRe_Student;
    private javax.swing.JMenuItem muRet_Book;
    private javax.swing.JMenuItem muTa_AudioVisual;
    private javax.swing.JMenuItem muTa_Books;
    private javax.swing.JMenuItem muTa_Students;
    private javax.swing.JMenu mu_Loans;
    private javax.swing.JMenu mu_Record;
    private javax.swing.JMenu mu_Returns;
    private javax.swing.JMenu mu_Tables;
    // End of variables declaration//GEN-END:variables
}
